/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jtable;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class AdminTable extends javax.swing.JFrame {

    /**
     * Creates new form AdminTable
     */
    public AdminTable() {
        initComponents();
        
    }
 
                   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PopUpForm = new javax.swing.JPopupMenu();
        Form = new javax.swing.JMenu();
        s_no = new javax.swing.JMenuItem();
        Org = new javax.swing.JMenuItem();
        time = new javax.swing.JMenuItem();
        date = new javax.swing.JMenuItem();
        venue = new javax.swing.JMenuItem();
        status = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admintable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Form.setText("jMenu1");

        s_no.setText("jMenuItem1");
        s_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_noActionPerformed(evt);
            }
        });
        Form.add(s_no);

        Org.setText("jMenuItem2");
        Form.add(Org);

        time.setText("jMenuItem3");
        Form.add(time);

        date.setText("jMenuItem4");
        Form.add(date);

        venue.setText("jMenuItem5");
        Form.add(venue);

        status.setText("jMenuItem6");
        Form.add(status);

        PopUpForm.add(Form);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admintable.setBackground(new java.awt.Color(204, 204, 255));
        Admintable.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Admintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORGANIZATION", "TIME", "DATE", "VENUE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Admintable.setRowHeight(35);
        Admintable.setShowGrid(true);
        jScrollPane1.setViewportView(Admintable);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD EVENT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_noActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here    
        try{
          Class.forName("com.mysql.jdbc.Driver");
          String url = "jdbc:mysql://localhost:3306/admin_table";
          String user="root";
          String pass="mark1000";
          Connection  con =DriverManager.getConnection(url,user,pass);
          String sql ="insert into admintable values(?,?,?,?,?)";
           PreparedStatement ptat = con.prepareStatement(sql);
             String m= JOptionPane.showInputDialog("Enter the Organization:-");
             String p = JOptionPane.showInputDialog("Enter the Time:-");
             String q =JOptionPane.showInputDialog("Enter the Date:-");
             String i =JOptionPane.showInputDialog("Enter the Venue:-");
             String t=JOptionPane.showInputDialog("Enter the Status:-");
             sql ="insert into admintable values(?,?,?,?,?)";
           ptat.setString(1,m);
           ptat.setString(2,p);
           ptat.setString(3,q);
           ptat.setString(4,i);
           ptat.setString(5,t);
           ptat.executeUpdate();
           JOptionPane.showMessageDialog(this,"Data stored in the table!!");
           String tbdata[]={m,p,q,i,t};
           DefaultTableModel tb1Model = (DefaultTableModel)Admintable.getModel();
           tb1Model.addRow(tbdata);
           con.close();
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
          Class.forName("com.mysql.jdbc.Driver");
          String url = "jdbc:mysql://localhost:3306/admin_table";
          String user="root";
          String pass="mark1000";
          Connection  con =DriverManager.getConnection(url,user,pass);
          String o=JOptionPane.showInputDialog("Enter organization name to update the event details:");
             String m= JOptionPane.showInputDialog("Enter the  New Organization:-");
             String p = JOptionPane.showInputDialog("Enter the New Time:-");
             String q =JOptionPane.showInputDialog("Enter the  New Date:-");
             String i =JOptionPane.showInputDialog("Enter the  New Venue:-");
             String t=JOptionPane.showInputDialog("Enter the New Status:-");
             String sql ="update admintable set Orgnization= ?,Time=?,Date=?,Venue=?,Status=?where Orgnization = '"+o+"'";
           PreparedStatement ptat = con.prepareStatement(sql);
           ptat.setString(1,m);
           ptat.setString(2,p);
           ptat.setString(3,q);
           ptat.setString(4,i);
           ptat.setString(5,t);
           ptat.execute();
           DefaultTableModel tb1Model = (DefaultTableModel)Admintable.getModel();
           for(int j=0; j<tb1Model.getRowCount();j++) {
           if (((String)tb1Model.getValueAt(j, 0)).equals(o)) {
           tb1Model.removeRow(j);
            }
           else{
               JOptionPane.showMessageDialog(this,"Error!");
           }
           
}
           JOptionPane.showMessageDialog(this,"Data updated!!!");
           JOptionPane.showMessageDialog(this,"Data stored in the table!!");
           String tbdata[]={m,p,q,i,t};
           tb1Model.addRow(tbdata);
           con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Admintable;
    private javax.swing.JMenu Form;
    private javax.swing.JMenuItem Org;
    private javax.swing.JPopupMenu PopUpForm;
    private javax.swing.JMenuItem date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem s_no;
    private javax.swing.JMenuItem status;
    private javax.swing.JMenuItem time;
    private javax.swing.JMenuItem venue;
    // End of variables declaration//GEN-END:variables
}
